---
require_auth: true
mail_from: tripleoresults@gmail.com
templates_path: template/
log_url: 'http://logs.openstack.org/periodic/'
api_server: 'http://tempest-sendmail.tripleo.org:8080/api/v1.0/sendmail'
use_api_server: true
default_log_url: 'http://logs.openstack.org'
emails:
  - mail: 'arxcruz@gmail.com'
    name: 'Arx Cruz'
template: template.html
