---
known_failures:
  - test: 'tempest.api.telemetry.test_telemetry_notification_api'
    reason: 'ospd-8 poodle 2016-02-04.1 tempest.api.telemetry.test_telemetry_notification_api failing'
    bz: 'https://bugzilla.redhat.com/show_bug.cgi?id=1304933'
  - test: 'tempest.scenario.test_volume_boot_pattern'
    reason: 'rdo-manager tempest smoke test failing on "floating ip pool not found"'
    bz: 'https://bugzilla.redhat.com/show_bug.cgi?id=1272289'
  - test: 'tempest.api.volume.test_volumes_get'
    reason: 'rdo-manager tempest smoke test failing on "floating ip pool not found"'
    bz: 'https://bugzilla.redhat.com/show_bug.cgi?id=1272289'
  - test: 'tempest.api.identity.*v3'
    reason: 'Tempest Identify tests failed on V3 api on OSP-D puddle'
    bz: 'https://bugzilla.redhat.com/show_bug.cgi?id=1266947'
  - test: 'tempest.api.data_processing'
    reason: 'tempest.api.data_processing tests failing on newton'
    bz: 'https://bugzilla.redhat.com/show_bug.cgi?id=1357667'
  - test: 'tempest.scenario.test_network_basic_ops.TestNetworkBasicOps'
    reason: 'TestNetworkBasicOps often times out running against tripleo'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1605654'
  - test: 'tempest.api.compute.servers.test_server_actions.ServerActionsTestJSON'
    reason: 'tempest fail: tempest.api.identity.admin.v2.test_services.ServicesTestJSON'
    bz: 'https://bugzilla.redhat.com/show_bug.cgi?id=1386421'
  - test: 'tempest.scenario.test_encrypted_cinder_volumes.TestEncryptedCinderVolumes.test_encrypted_cinder_volumes_cryptsetup'
    reason: 'TripleO does not deploy Barbican by default, which is needed for this test to pass'
  - test: 'tempest.scenario.test_encrypted_cinder_volumes.TestEncryptedCinderVolumes.test_encrypted_cinder_volumes_luks'
    reason: 'TripleO does not deploy Barbican by default, which is needed for this test to pass'
  - test: 'tempest.scenario.test_security_groups_basic_ops.TestSecurityGroupsBasicOps.test_cross_tenant_traffic'
    reason: 'Security groups firewall rules do not get applied on the compute nodes'
    bz: 'https://bugzilla.redhat.com/show_bug.cgi?id=1411690'
  - test: 'tempest.scenario.test_security_groups_basic_ops.TestSecurityGroupsBasicOps.test_multiple_security_groups'
    reason: 'Security groups firewall rules do not get applied on the compute nodes'
    bz: 'https://bugzilla.redhat.com/show_bug.cgi?id=1411690'
  - test: 'mistral_tempest_tests.tests'
    reason: 'Skip Mistral tests as it needs to use mistral v2 endpoints'
  - test: 'ceilometer.tests.tempest.api.test_telemetry_notification_api.TelemetryNotificationAPITest'
    reason: 'This telemetry installation is configured to use Gnocchi'
  - test: 'ceilometer.tests.tempest.api.test_telemetry_notification_api.TelemetryNotificationAdminAPITest'
    reason: 'This telemetry installation is configured to use Gnocchi'
  - test: 'ceilometer.tests.tempest.scenario.test_object_storage_telemetry_middleware.TestObjectStorageTelemetry'
    reason: 'This telemetry installation is configured to use Gnocchi'
  - test: 'neutron.tests.tempest.scenario.test_dvr.NetworkDvrTest'
    reason: 'TODO(arxcruz) New test, need investigation'
  - test: 'neutron.tests.tempest.scenario.test_trunk.TrunkTest'
    reason: 'TODO(arxcruz) New test, need investigation'
  # skip list for undercloud
  - test: 'tempest.api.network.test_networks.NetworksTest.test_external_network_visibility'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.test_floating_ips.FloatingIPTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.servers'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_aggregates_negative.AggregatesAdminNegativeTestJSON.test_aggregate_add_existent_host'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_aggregates_negative.AggregatesAdminNegativeTestJSON.test_aggregate_add_host_as_user'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_aggregates_negative.AggregatesAdminNegativeTestJSON.test_aggregate_remove_host_as_user'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_create_server.ServersWithSpecificFlavorTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_aggregates.AggregatesAdminTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_create_server.ServersWithSpecificFlavorTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_hypervisor'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_hypervisor_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_delete_server'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_hosts.HostsAdminTestJSON.test_show_host_detail'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_servers'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_simple_tenant_usage'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_servers_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.floating_ips'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_server_diagnostics'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_server_diagnostics_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.images'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_external_networks_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_floating_ips_admin_actions'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_routers'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_routers_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.test_floating_ips_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.test_networks.NetworksIpV6Test.test_external_network_visibility'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_ports'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.security_groups.test_security_groups.SecurityGroupsTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.admin.v3.test_roles.RolesV3TestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.admin.v2.test_endpoints'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.admin.v2.test_roles'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.test_tags'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.admin.v2.test_roles_negative.RolesNegativeTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.admin.v2.test_services.ServicesTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.admin.v2.test_tenant_negative.TenantsNegativeTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.admin.v2.test_tenants.TenantsTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.admin.v2.test_tokens.TokensTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.admin.v2.test_users.UsersTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.admin.v2.test_users_negative.UsersNegativeTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.test_dhcp_ipv6.NetworksTestDHCPv6'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.test_ports.PortsTestJSON.test_port_list_filter_by_router_id'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.test_ports.PortsIpV6TestJSON.test_port_list_filter_by_router_id'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.image.v1.test_images'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_baremetal_nodes.BaremetalNodesAdminTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.image.v1.test_images.CreateRegisterImagesTest'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_external_network_extension.ExternalNetworksTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
