#!/bin/bash
set -eux
TMPDIR='/tmp/dci-tmp-dir'
BASEDIR=$(pwd)

if [ $# -ne 2 ] || [ "$1" != "--rhgerrit-user" ]; then
    echo "Missing '--rhgerrit-user <your_username>'"
    exit 1
fi

RHGERRIT_USER=$2

declare -A release
release['OSP10']='newton'
release['OSP11']='ocata'
release['OSP12']='pike'
release['OSP13']='queens'
release['OSP14']='rocky'
release['OSP15']='stein'
release['OSP16']='train'

get_repo() {
    repo=${1}
    roles=${2}
    pushd ${TMPDIR}
    git clone https://code.engineering.redhat.com/gerrit/${repo}.git ${repo}
    cd ${repo}
    for topic in "${!release[@]}"; do
        branch=$(echo ${topic}|sed 's,OSP,origin/stable/rhos-,')

        # Override branch name for current unreleased version
        if [ "${branch}" = "origin/stable/rhos-15" -o "${branch}" = "origin/stable/rhos-16" ]; then
            branch="origin/master"
        fi

        target=${BASEDIR}/roles/${release[$topic]}
        mkdir -p ${target}
        git checkout -b ${topic} ${branch}

        if [ ${repo} = 'tripleo-quickstart-extras' ]; then
            git remote show redhat_gerrit || git remote add redhat_gerrit ssh://${RHGERRIT_USER}@code.engineering.redhat.com:22/tripleo-quickstart-extras.git
            [ ${topic} = "OSP10" ] && git review -r redhat_gerrit -x 185774
            [ ${topic} = "OSP15" -o ${topic} = "OSP16" ] && git review -x 676196
            [ ${topic} = "OSP16" ] && git review -x 718353

            git review -x 716237
        fi

        for i in ${roles}; do
           if [ "${i}" == "tripleo-validations" ] && ([ "${topic}" == "OSP8" ] || [ "${topic}" == "OSP9" ]); then
               continue
           else
               cp -av roles/${i} ${target}/${i}
           fi
        done
	git reset --hard
	git clean -ffdx
    done
    popd
}

#
# main()
#

# Do some cleanup
rm -Rf ${TMPDIR} ${BASEDIR}/roles
mkdir -p ${TMPDIR}

# Fetch the required roles into each release folder
get_repo tripleo-quickstart "common tripleo-inventory"
get_repo tripleo-quickstart-extras "extras-common tripleo-validations validate-tempest"

# We're using the same collect-logs role for all versions, keep only the latest one
git clone --depth=1 --branch=master https://github.com/openstack/ansible-role-collect-logs "${BASEDIR}"/roles/collect-logs
rm -rf "${BASEDIR}"/roles/collect-logs/.git

# Finally add everything to staged area for review before commiting
git add roles
