---
# Initial Step:
#
# Schedule a new job giving a specific topic and specifying the remote CI.
# The return of this action contains all the data associated with the job,
# we hence register those data for later consumptions
#
- hosts: localhost
  tags:
    - job
  tasks:
    - name: Schedule a new job
      dci_job:
        components: '{{ dci_components|default([]) }}'
        topic: '{{ dci_topic }}'
        # id: '88fbd033-07b5-4cce-bb71-f320276cb0d0'
        # embed: 'remoteci,rconfiguration,topic,components'
      register: job_informations

    - set_fact:
        job_id: '{{ hostvars.localhost.job_informations.job.id }}'
    - name: Set the metadata
      dci_job:
        id: "{{ job_informations.job.id }}"
        metadata: '{{ dci_metadata }}'
      when: dci_metadata is defined and dci_metadata
    - copy: content="{{ job_informations|to_nice_yaml }}" dest=/var/lib/dci-openstack-agent/job_info.yaml
