---
dependencies:
  - common

galaxy_info:
  author: Red Hat
  description: |
    This Ansible role contains defaults for variables used in more than 2 roles
    throughout the tripleo-quickstart-extras repository. All other roles in this
    repository depend on this one.
  license: Apache
  platforms:
    - name: CentOS
      versions:
        - 7
        - 8
    - name: EL
      versions:
        - 7
        - 8
  min_ansible_version: 2.8
