---
- project:
    templates:
      - tripleo-standalone-scenarios-full
      - tripleo-undercloud-jobs
      - tripleo-multinode-container-full
    check:
      jobs:
        - openstack-tox-linters
        - openstack-tox-molecule
    gate:
      jobs:
        - openstack-tox-linters
        - openstack-tox-molecule
      queue: tripleo
    post:
      jobs:
        - publish-openstack-python-branch-tarball
