---
- name: Check for .stestr directory
  stat:
    path: "{{ working_dir }}/tempest/.stestr"
  register: testr_dir

- name: Define testr facts
  set_fact:
    testr_command: testr
    testr_dir: .testrepository
  when: not testr_dir.stat.exists

- name: Define stestr facts
  set_fact:
    testr_command: stestr
    testr_dir: .stestr
  when: testr_dir.stat.exists
