---
## PLEASE READ ##
## Do not add tests to the skip list that are in    ##
## featureset016 - featureset019 w/o permission from ##
## the TripleO PTL, Thanks                          ##

known_failures:
  - test: 'neutron_tempest_plugin.scenario.test_floatingip.FloatingIPQosTest.test_qos'
    reason: 'Neutron Tempest plugin scenario tests are not yet stable.'
    lp: 'https://launchpad.net/bugs/1737940'
  - test: 'tempest.scenario.test_security_groups_basic_ops.TestSecurityGroupsBasicOps.test_boot_into_disabled_port_security_network_without_secgroup'
    reason: 'Failed to boot servers on different Compute nodes'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1857365'
  - test: 'tempest.scenario.test_security_groups_basic_ops.TestSecurityGroupsBasicOps.test_port_update_new_security_group'
    reason: 'Failed to boot servers on different Compute nodes'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1857365'
  - test: 'tempest.api.compute.admin.test_servers_on_multinodes.ServersOnMultiNodesTest.test_create_servers_on_same_host'
    reason: 'Errors with servres on multiple nodes'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1857365'
  - test: 'neutron_tempest_plugin.scenario.test_qos.QoSTest'
    reason: 'Neutron Tempest plugin scenario tests are not yet stable.'
    lp: 'https://launchpad.net/bugs/1737940'
  - test: 'patrole_tempest_plugin'
    reason: 'Not supported in TripleO/tempestconf'
  - test: 'zaqar_tempest_plugin'
    reason: 'Not supported in TripleO/tempestconf'
  - test: 'watcher_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'vitrage_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'trove_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'tripleo_common_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'tempest_horizon'
    reason: 'Not supported in TripleO'
  - test: 'octavia_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'murano_tempest_tests'
    reason: 'Not supported in TripleO'
  - test: 'mistral_tempest_tests'
    reason: 'Not supported in TripleO'
  - test: 'magnum_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'kuryr_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'ironic_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'heat_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'designate_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'congress_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'barbican_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'ec2api_tempest_plugin'
    reason: 'Not supported in TripleO/tempestconf'
  - test: 'neutron_tempest_plugin.api.test_trunk_negative.TrunkTestMtusJSON'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_security_groups.RbacSharedSecurityGroupTest'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_routers_negative.DvrRoutersNegativeTestExtended'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_routers_negative.DvrRoutersNegativeTest'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_routers.DvrRoutersTestToCentralized'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_routers.DvrRoutersTestUpdateDistributedExtended'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_routers.DvrRoutersTest'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_qos.QosMinimumBandwidthRuleTestJSON'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_ports.PortsTestJSON'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_floating_ips.FloatingIPPoolTestJSON'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'tempest.api.compute.admin.test_auto_allocate_network.AutoAllocateNetworkTest.test_server_multi_create_auto_allocate'
    reason: 'Test is failing due to microversion'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1821690'

  # skip list for undercloud
  - test: 'tempest.api.network.test_networks.NetworksTest.test_external_network_visibility'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.test_floating_ips.FloatingIPTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.servers'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_aggregates_negative.AggregatesAdminNegativeTestJSON.test_aggregate_add_existent_host'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_aggregates_negative.AggregatesAdminNegativeTestJSON.test_aggregate_add_host_as_user'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_aggregates_negative.AggregatesAdminNegativeTestJSON.test_aggregate_remove_host_as_user'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_create_server.ServersWithSpecificFlavorTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_aggregates.AggregatesAdminTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_create_server.ServersWithSpecificFlavorTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_hypervisor'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_hypervisor_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_delete_server'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_hosts.HostsAdminTestJSON.test_show_host_detail'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_servers'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_simple_tenant_usage'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_servers_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.floating_ips'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_server_diagnostics'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_server_diagnostics_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.images'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_external_networks_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_floating_ips_admin_actions'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_routers'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_routers_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.test_floating_ips_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.test_networks.NetworksIpV6Test.test_external_network_visibility'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_ports'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.security_groups.test_security_groups.SecurityGroupsTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.admin.v3.test_roles.RolesV3TestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'vitrage_tempest_plugin'
    reason: 'Not supported in TripleO Undercloud'
    undercloud: true
