---
- include: tempest-venv.yml
  when: tempest_config|bool and tempest_format == 'venv'
  tags:
    - pre-tempest-config

- include: tempest-rpm.yml
  when: tempest_config|bool and tempest_format == 'packages'
  tags:
    - pre-tempest-config

- include: tempest-containers.yml
  when: tempest_config|bool and tempest_format == 'container'
  tags:
    - pre-tempest-config

- include: pre-tempest.yml
  when: tempest_config|bool or run_tempest|bool
  tags:
    - pre-tempest-config

- include: run-tempest.yml
  when: run_tempest|bool
  tags:
    - run-tempest

- include: stackviz.yml
  when: run_tempest|bool
  tags:
    - run-stackviz
  ignore_errors: yes

- include: post-tempest.yml
  when: post_tempest|bool and run_tempest|bool
  tags:
    - post-tempest
